### ISSUE TITLE
Generation fails when humans are the only race that's common and all others are set to None

### ISSUE THREAD

**Issue by KatAKlettke** [Praxxian/RPG-City-Generator#1]
As the title states. Not touching the race distribution generates a settlement, but if I change it to a human-only settlement generating seems to only reload the page, no error message or anything generated. Tested with Extra-Small and Small Village and Agriculture chosen.

Have tested it with Firefox 84.0.1, 87.0, Chrome 89.0.4389.114, and 89.0.4389.128 (all 64bit) on WIndows 10.

**Comment by Praxxian** [comment]
Thank you for your feedback! The issue should now be fixed. If you can still reproduce it, you may need to refresh with shift+F5.
