### ISSUE TITLE
Lacking Spouse Information

### ISSUE THREAD

**Issue by JamesPildis** [Praxxian/RPG-City-Generator#14]
Clicking the "download" button creates a sheet missing some information, namely the character's spouse and their owned business/job

**Comment by Praxxian** [comment]
The owned business is the last column, but I do see that sometimes it shows the name, and sometimes the ID. Very weird that it is inconsistent because it is all based on overriding toString() for that class. I see spouse is missing, too.

**Comment by Praxxian** [comment]
The fix for this is now live. Thanks again for your feedback!
