### ISSUE TITLE
Gender Selection Mismatch

### ISSUE THREAD

**Issue by JamesPildis** [Praxxian/RPG-City-Generator#15]
Non-Binary and Gender-Fluid still appears in city spreadsheets that were prompted to only have male/female characters

**Comment by Praxxian** [comment]
I gave this a couple of tries, but I was not able to reproduce. Are there any particular steps? Here is what I did:

1. Set city size to Town.
2. Unclicked Gender-fluid and non-binary
3. Clicked Generate
4. Clicked Download

**Comment by JamesPildis** [comment]
I believe mine was after setting to City with the same other steps

**Comment by Praxxian** [comment]
I still was not able to reproduce. Does this happen every time, or was this a one-off? Does it still occur?

**Comment by Praxxian** [comment]
Apologies for the long wait. I have had some family stuff going on and have not been able to work on the project for a little while. I very much would like to get back to maintaining it, so thank you for your patience.

Are you still able to reproduce this issue? If so, could you provide some steps? Thanks!
