### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by CHillAaron** [Praxxian/RPG-City-Generator#3]
I was wondering if you minded if I use this on a personal project. This is almost exactly what I am looking for. 

I did not know how to contact or send an actual request.

Thank you

**Comment by Praxxian** [comment]
Generally I have no problem with that. I made this for people to use in
their games. What kind of project are you working on?

**Comment by CHillAaron** [comment]
Long story short it is a world building app for my DND campaign. 
Something to help me learn more on coding and to flourish my hobby lol

**Comment by Praxxian** [comment]
If you're just using data generated from the app, yeah use whatever you
want. If you are using code, please just provide attribution in a README
file, thanks!

**Comment by CHillAaron** [comment]
Honestly, I was going to do that either way. Having the link to your page. Thank you again!

**Comment by Praxxian** [comment]
Good luck and have fun!
