### ISSUE TITLE
Races Bugged when Lowering Human From Common

### ISSUE THREAD

**Issue by PerezMH** [Praxxian/RPG-City-Generator#4]
I was fiddling around with your excellent generator and encountered an error message when I lowered Humans from Common to Uncommon. Unfortunately I didn't have the foresight to screencap that error message for you and I have since been unable to make it appear again upon generating. Now whenever I generate, regardless of my settings on the side, the race column remains empty for all residents except for 3 or 4 races. I've included a screenshot to show you the settings I tested with and I filtered the race column to show which residents have a race and how the rest do not. 
![image](https://user-images.githubusercontent.com/66839437/139528923-559a82ee-05a1-4846-bd80-0b1660a9efa0.png)

I'm thinking it's a bug on my browser side somehow but I'm hoping you might be aware of what the issue might be. I've been using your tool for a little bit now to help with my custom campaign I'm running and it's been tremendously helpful with city planning. Thank you for all you do.
Cheers
Enzo

**Comment by PerezMH** [comment]
I actually managed to catch the error message finally by opening in the site with a different browser. It appears twice and then finishes generating, providing a screenshot like the one above.

`DataTables warning: table id=people_table - Requested unknown parameter '2' for row 0, column 2. For more information about this error, please see http://datatables.net/tn/4`

Hope the error message helps!

**Comment by Praxxian** [comment]
Thanks for providing those details! Which browsers were you able to reproduce the issue in?

It is odd that the issue occurs and appears to cause other unexpected behavior. My own code does not store anything locally, but maybe DataTables does. For temporary relief, you could try refreshing your cache and the page by using Ctrl+F5 when you see the issue.

**Comment by Praxxian** [comment]
Actually, ignore that question. I see what the issue is. There's no "common" race selected, which is throwing things off.

Since it is not clear what the intended behavior of a user who does not select a common race should be, I think I will warn the user to set one before generating a city.

**Comment by Praxxian** [comment]
The page will now warn you if you have not selected at least one common race. Thanks for your feedback!
