### ISSUE TITLE
Stats Wheel

### ISSUE THREAD

**Issue by Zerifore** [Praxxian/RPG-City-Generator#5]
The population breakdown wheel glitches out and will not work properly. Otherwise an amazing website!

**Comment by Praxxian** [comment]
Do you have steps to reproduce and/or a screenshot of the behavior? It would also be helpful to know your browser. Thanks!

**Comment by Zerifore** [comment]
I am using good chrome. There are not really any steps involved it is basically either not loading or when it does it moves around, making it unable to see the numbers and changing color rapidly when hovering over it.

**Comment by Praxxian** [comment]
Do you have a screenshot you could share? I use Chrome a lot, too, and I have not been able to reproduce.

**Comment by Dunedain-Sam** [comment]
I think you can reproduce this by:
Generate city
Generate another city with different population criteria
Hover over parts of the pie chart
> Some will appear to show the previous town distrobution
