### ISSUE TITLE
Higher User Control

### ISSUE THREAD

**Issue by JamesPildis** [Praxxian/RPG-City-Generator#7]
Hello!  I absolutely love this tool and it has been a MAJOR help in creating my large homebrew campaign!

I was wondering if you had considered giving users the ability to alter the following:

1.)  Add races to the list of available slots for a given town.  Essentially a user would be able to add a set amount of homebrew races, official content not included by the tool, etc.

2.)  Direct population size adjustment.  Having the village/town/city drop down menu is great, but there's a really large gap between wanted a few hundred-thousand and then having to jump into ~25,000 territory.  A user-input number for total population would help with this.

3.)  Select which genders are available at each location.  Allowing a user to decide if they solely want male/female populations, no gender at all, a village run entirely by women, and so on.

4.)  On top of the ability to select resources (rivers allowing fishermen, forests allowing lumberjacks, etc.), is it possible to select the availability of magic in a given town or city?  Essentially putting a limit to the items in shops, the types of shops, etc.

Again, I absolutely love this tool and would love to see it grow.  If you ever consider to make a paid, downloadable application with higher functionality I would love to support your work!

**Comment by Praxxian** [comment]
Thank you for the feedback! I have a pretty good idea how I would implement 1-3. 4 is a little tricky. There was another feature request for this as well, and I have been thinking about what the scope of that would be. Pricing magic items is a notorious problem. The ranges from WotC are pretty wild. I have been toying with a few methodologies that are easier than me sitting down and pricing everything individually.

It is intuitive to expect magic to have different levels: none, low, and high. I am thinking about how this would translate into what would be available. It would probably break down to frequency of magical locations (wizard tower, paladin order, druid circle, etc) and availability of magic items. But let me know if you had other expectations as how this would affect the town.

I would love to keep this tool free and available to all as a way to pay it forward for all the excellent free tools I use myself.

**Comment by JamesPildis** [comment]
I think it's worth noting that magical items as a whole are recommended not to be sold in D&D for that reason, more as rewards for quests and exploring dungeons.  I think those separate buildings would be cool, maybe updates to the shop structure to include something like a Wizard Tower or some other unique building that people would recognize and be wroth noting on the town map.  My note for the magic resource was more towards limiting things like potions/magical herbs in shops but those can easily be omitted in the .csv file.  

Really excited to see what comes with future updates, this application is a life saver with homebrew content!

**Comment by Praxxian** [comment]
Implemented the Gender selection feature.

**Comment by Praxxian** [comment]
Going to break this issue up:
https://github.com/Praxxian/RPG-City-Generator/issues/11
https://github.com/Praxxian/RPG-City-Generator/issues/12

Magic stuff:
https://github.com/Praxxian/RPG-City-Generator/issues/8
https://github.com/Praxxian/RPG-City-Generator/issues/9
